### ISSUE TITLE
NFC Security

### ISSUE THREAD

**Issue by nk521** [bangpypers/meetup-talks#1]
### Title of the talk

NFC Security

### Description

NFC is widely used for authentication purposes. For example: NFC gate pass, NFC based rail ticketing, etc. But how secure real world NFC based authentication really is? I did a research, which lasted 2 years, to break into one of the major rail service in Delhi, DMRC. I was able to successfully recharge cards for free and travel for free and much more.

My talk will go into really basics of a communication technology and how to break it. Please note that its not going to be a NFC 101, I’ll only talk about a particular family of MIFARE NFC cards called MIFARE DESFIRE cards which are encrypted.

The story was also published in TechCrunch - https://techcrunch.com/2022/11/02/india-delhi-metro-smart-card-bug/

### What format do you have in mind for your talk?

Talk

### Table of contents

* What is NFC and How it works?
* Small chat about ISO14443 standard
* The beloved MIFARE DESFire EV1 card
* A hacky way to pentest
* ???
* Profit

### What domain would you say your talk falls under?

Research

### Duration in minutes (including Q&A)

60

### Speaker bio

Twitter: [@dumbomason](https://twitter.com/dumbomason)
LinkedIn: [@nk521](https://www.linkedin.com/in/nk521/)

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [ ] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi @nk521 

Please confirm if you want to present this talk at [this month's meetup](https://www.meetup.com/bangpypers/events/whqxvsyfcfbxb/)?

**Comment by nk521** [comment]
Sure. I can present on 18th.
