### ISSUE TITLE
Talking to USB with Python

### ISSUE THREAD

**Issue by nk521** [bangpypers/meetup-talks#10]
### Title of the talk

Talking to USB with Python

### Description

About a small project I did on how to control OSD menu of a gigabyte monitor using the provided USB cable. Gigabyte ships there own software for this but you can reverse engineer the communication and implement it again in python!

This is not a USB 101. Although I give required context before hand!

### What format do you have in mind for your talk?

Talk

### Table of contents

1. Understanding how Gigabyte's OSD controller works.
2. Reversing the communication using wireshark
3. LibUSB
4. How to use LibUSB in Python
5. How to do a control transfer

### What domain would you say your talk falls under?

Embedded

### Duration in minutes (including Q&A)

30

### Prerequisites

If you understand basic syntax of python, you should be good to go.

### Speaker bio

Twitter: [@dumbomason](https://twitter.com/dumbomason)
LinkedIn: [@nk521](https://www.linkedin.com/in/nk521/)

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)
- [ ] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

**Comment by anistark** [comment]
Hi @nk521 
Are you willing to present this in July meetup?

**Comment by nk521** [comment]
@anistark, Sure. Though it depends on the venue.

**Comment by RiteshAgrawal** [comment]
@nk521 Venue is Cyware labs, HSR Layout. Please confirm your availability.

**Comment by nk521** [comment]
@RiteshAgrawal Works for me.

**Comment by anistark** [comment]
Thanks for confirming @nk521 
Could you please also share your pic to be used in the promotional banner if you're ok with it?

**Comment by nk521** [comment]
@anistark is it possible for you to do it without my face? You can use my name (Nikhil) and my nickname (mason) to denote me anywhere.

**Comment by anistark** [comment]
@nk521 

Of course can leave it blanked. Any particular reason though? 
Had taken pic from your LinkedIn: https://www.meetup.com/bangpypers/events/whqxvsyfckbtb/ 

Will remove it if you don't like it.

**Comment by nk521** [comment]
No need to remove if you've already used the image.
