### ISSUE TITLE
Introduction to the biotite python package

### ISSUE THREAD

**Issue by BioinfoGuy10** [bangpypers/meetup-talks#11]
### Title of the talk

Introduction to the biotite python package

### Description

I would like to introduce the bioitite package.
1) Sequence alignment
2) Finding gene homologs
3) Biological assembly of a structure

### What format do you have in mind for your talk?

Talk

### Table of contents

I would like to introduce the bioitite package.
1) Sequence alignment
2) Finding gene homologs
3) Biological assembly of a structure

### What domain would you say your talk falls under?

Research

### Duration in minutes (including Q&A)

25

### Speaker bio

LinkedIn:https://www.linkedin.com/in/keith-saldanha-3bb590aa/

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by RiteshAgrawal** [comment]
Hi @BioinfoGuy10 
Would you be able to present the talk on aug meetup (19th Aug)

**Comment by BioinfoGuy10** [comment]
Hi Ritesh,
apologies but I have to withdraw this topic.
