### ISSUE TITLE
Introduction to Graph Neural Networks

### ISSUE THREAD

**Issue by SauravMaheshkar** [bangpypers/meetup-talks#12]
### Title of the talk

Introduction to Graph Neural Networks

### Description

This talk will provide an introduction to Graph Neural Networks and motivate their usage. We will go through a brief overview of the various classes of networks i.e. message passing networks, graph convolutional networks, and graph attention networks, and talk about each of them in detail. We will discuss the strengths and weaknesses of each type of networks and how they can be used for different tasks. 

### What format do you have in mind for your talk?

Talk

### Table of contents

* Basic Introduction to Graphs and key terms related to them
* Motivation behind Graph Neural Networks
* Brief Overview of the various classes of networks
* Overview of Message Passing Graph Neural Networks
* Overview of Graph Convolutional Networks
* Overview of Graph Attention Networks
* Recommended Reading and Next Steps

### What domain would you say your talk falls under?

Data Science & Machine Learning

### Duration in minutes (including Q&A)

40-60

### Prerequisites

Basic background knowledge about Machine Learning, no advanced knowledge about maths or deep learning is required. 

### Speaker bio

Saurav Maheshkar is a Research Machine Learning Engineer at Re:courseAI, where he works on Geometric Deep Learning. He studies Computer Science at the University of Manchester with a passion for geometric learning and self-supervised learning. He is currently working on developing self-supervised learning methods for graphs, and is also interested in benchmarking self-supervised learning methods and knowledge distillation methods.

Twitter/X: [@MaheshkarSaurav](https://twitter.com/MaheshkarSaurav)
LinkedIn: [Saurav Maheshkar](https://www.linkedin.com/in/sauravmaheshkar/)

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by RiteshAgrawal** [comment]
Hi @SauravMaheshkar 
Would you be able to present the talk in Aug meetup (19th Aug)?

**Comment by SauravMaheshkar** [comment]
Hey @RiteshAgrawal, I actually just confirmed myself as a speaker at the Docker Meetup on the same day 😅 .
