### ISSUE TITLE
What Happens Inside Flask? From Setup to Serving the First Request.

### ISSUE THREAD

**Issue by abhirathmahipal** [bangpypers/meetup-talks#14]
### Title of the talk

What Happens Inside Flask? From Setup to Serving the First Request.

### Description

We all know how a web server works at a higher level (forever keeps waiting for a request, parses the request, calls the corresponding handler, returns a response).

Flask is a beloved and popular web server. To top it, the code base is pretty small and accesssible.

Let's decipher (layer by layer) what exactly happens right from the initialisation stages to serving it's very first request

### What format do you have in mind for your talk?

Talk

### Table of contents

- Basic Flask Classes and Functions
- What Happens During Setup?
- Some Code Patterns
- Serving Requests
- Why are WSGI/ASGI needed?
- Integration with WSGI Servers (Werkzeug)

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

30

### Prerequisites

None needed. It'd be great if you've used Flask though.

### Speaker bio

I am Abhirath and I love building stuff. I currently work at Amazon and outside of work you can find me dabbling with open source code, working on pet projects or just whiling away time.

I sometimes blog at [csjourney.com](https://www.csjourney.com).

[LinkedIn](https://www.linkedin.com/in/abhirathmahipal/)

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by abhirathmahipal** [comment]
I'd like to give the talk on Sep 16, 2023.

**Comment by anistark** [comment]
@abhirathmahipal Would you be willing to do this session on Nov 25th meetup?

**Comment by anistark** [comment]
@abhirathmahipal Gentle reminder to confirm.

**Comment by anistark** [comment]
No response. Closing it.
