### ISSUE TITLE
Deep Dive in to Diffusion Models

### ISSUE THREAD

**Issue by varskann** [bangpypers/meetup-talks#15]
### Title of the talk

Deep Dive in to Diffusion Models

### Description

Introduction, Maths, and Training Diffusion Models. Presentation, Walk Through, and Other details on how Diffusion Models Work.

A workshop can be hosted if people show interest in the talk

### What format do you have in mind for your talk?

Talk

### Table of contents

Agenda: 
- Popular Diffusion Models
- Diffusion Models capabilities, Use cases, shortcomings, etc.
- Using opensource Python Libraries to train, deploy custom/ Personal diffusion moels
- Training a diffusion model
- Maths behind diffusion models

### What domain would you say your talk falls under?

Data Science & Machine Learning

### Duration in minutes (including Q&A)

45

### Prerequisites

Basics of Machine Learning

### Speaker bio

https://www.linkedin.com/in/varskann/

Working as Staff DS with one of the Cutting edge Saas companies in AI, with over 8 years of experience in the field

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@varskann Would you be willing to do this session on Nov 25th meetup?

**Comment by anistark** [comment]
@varskann Gentle reminder to confirm.

**Comment by varskann** [comment]
Hello,

I didn't receive any confirmation email before last week! I have come to my
native now and haven't planned for the presentation due to no confirmation!

I can plan for next month, if I can get some prior confirmation for the the
presentation eligibilty

Thanks,
Kanishk Varshney

**Comment by anistark** [comment]
@varskann Can you present on Dec 16th meetup?

**Comment by varskann** [comment]
@anistark  I won't be in Bangalore for this week. Is it going to be an online talk?

**Comment by anistark** [comment]
> @anistark I won't be in Bangalore for this week. Is it going to be an online talk?

No. It's only offline.

**Comment by varskann** [comment]
Oh, When is the Jan meetup? Can prepare the deck for that

**Comment by anistark** [comment]
Hey @varskann 

Jan meetup is on 20th. Would you be presenting in it?

**Comment by varskann** [comment]
@anistark  you will have to update me a bit earlier. Let's do this, I am assuming Feb meetup will be on 20th? I will present in that meetup? Does that work for you?

**Comment by anistark** [comment]
Haven't planned for Feb meetup yet. Anyway, it'll be on 17th, if happens. But can only confirm closer to date. If you're visiting the city, it's fine. Or I'm sure there's a local python meetup where you can present your talk.

Closing this issue for now given it's been hanging for a while. If you're in the city, do feel free to reopen or submit new.

**Comment by varskann** [comment]
No no, I am stay in Bangalore only, just traveling once a month.
Coincidently the dates are clashing with your meetups.

I can start preparing for February one just in case... I have partial
material ready.

Thanks
