### ISSUE TITLE
Talk proposal: Making Python much faster, using type hints

### ISSUE THREAD

**Issue by tusharsadhwani** [bangpypers/meetup-talks#16]
### Title of the talk

Making Python much faster, using type hints

### Description

Python 3.0 had silently added a little feature to the language that, at the time, had no actual use case: you could now add "annotations" to your functions.

Fast forward 15 years, there is now a thriving community of developers and projects that have adopted the feature to add "type hints" to your code, and find bugs with highly sophisticated type checking tools.

Today, Python's type system is powerful enough that optimizations can automatically be done to the code based on these hints. We will learn how to do exactly that, with a tool called `mypyc`.

### What format do you have in mind for your talk?

Talk

### Table of contents

- Type hints: the what and the why
- Checking your type hints with `mypy`
- "Compiling" your code with `mypyc`
- Bonus: speed up your Python code with **zero type hints**.

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

1 hour

### Prerequisites

No pre requisites as such. Basic understanding of Python is needed to follow along.

### Speaker bio

Long term Python user, contributor, author and speaker.

I've contributed to various Python and PSF projects, such as cpython, black, mypy, pip, and pypi.org.

Currently working at DeepSource, maintaining their Python code analysis stack.

Blog: https://tushar.lol
Twitter: https://twitter.com/tusharisanerd

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@tusharsadhwani Would you be willing to do this session on Nov 25th meetup?

**Comment by tusharsadhwani** [comment]
@anistark i have a flight at 6pm that day. so if it's an evening event I can't

**Comment by anistark** [comment]
We'll most probably keep it in morning and most likely to happen in HSR if it helps.

**Comment by tusharsadhwani** [comment]
@anistark morning and HSR works for me.
