### ISSUE TITLE
Stream processing in Python

### ISSUE THREAD

**Issue by rahulpyd** [bangpypers/meetup-talks#18]
### Title of the talk

Stream processing in Python

### Description

In this talk we introduce reactive streams. We look at how we can process asynchronous streams of data/events in Python using Reactive Extensions library. We can look at various examples and patterns for reactive programming.

https://reactivex.io/
https://github.com/ReactiveX/RxPY

The talk assumes no prior knowledge of reactive programming.  A beginner level experience in Python would suffice.

### What format do you have in mind for your talk?

Talk

### Table of contents

- Introduction to reactive programming and reactive streams
- Introduction to RxPy (ReactiveX for Python)
- Examples/patterns for asynchronous stream processing in Python

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

50mins

### Prerequisites

The talk is beginner friendly. Some familiarity of asynchronous/event-driven programming would help. 

### Speaker bio

I am a technical founder at Art of Programming Edulabs. I previously worked as a senior engineer at Slice and Zynga. I am interested in building scalable and fault-tolerant backend systems. I spoke at various meetup groups including BangPypers, BangML and Deeplearning Bangalore in the past.

 www.linkedin.com/in/rahulpyd
https://github.com/rahulpyd

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@rahulpyd Are you available to deliver this talk on Dec 16th meetup?
