### ISSUE TITLE
ML model deployment with Triton Inference Server

### ISSUE THREAD

**Issue by rohitgr7** [bangpypers/meetup-talks#2]
### Title of the talk

ML model deployment with Triton Inference Server

### Description

NVIDIA Triton Inference Server is open-source inference-serving software that helps standardize model deployment and execution and delivers fast and scalable AI in production. I'll talk about its features, and capabilities and a code walkthrough to showcase how this framework can be used for model inferencing.

### What format do you have in mind for your talk?

Talk

### Table of contents

1. Intro to Triton Inference server
2. Functionalities it offers and how to configure it
3. Showcase an example on an ML model using a Jupyter notebook
4. My learnings while working with it

### What domain would you say your talk falls under?

Data Science & Machine Learning

### Duration in minutes (including Q&A)

30

### Prerequisites

Basic knowledge of python and pytorch (optional).

### Speaker bio

Twitter: https://twitter.com/imgrohit
LinkedIn: https://linkedin.com/in/rohitgr7

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@rohitgr7 Would you like to present this talk this weekend at [FOSS Hack](https://fossunited.org/fosshack/2023) ?

**Comment by rohitgr7** [comment]
I presented this talk at the last foss united meetup.

**Comment by RiyaMathew-11** [comment]
Hi @rohitgr7, you can have a sort of extended presentation about the same at FOSS Hack too. If you are interested, we can connect on [Telegram](https://t.me/m_riya11) and discuss more on the same. 

This is actually on 4th March (tomorrow) - and we are expecting the interaction to happen at night - post 9 pm.

**Comment by anistark** [comment]
Hi @rohitgr7 

Please confirm if you want to present this talk at [this month's meetup](https://www.meetup.com/bangpypers/events/whqxvsyfcfbxb/)?

**Comment by rohitgr7** [comment]
hey @anistark !

little busy this weekend? maybe next month?

**Comment by anistark** [comment]
@rohitgr7 Do you want to present in this month's meetup? It's on 20th morning.

**Comment by rohitgr7** [comment]
Hey @anistark !
Not in the city this month. But next month definitely :)

**Comment by anistark** [comment]
Hi @rohitgr7 

Are you willing to present this in July meetup?

**Comment by rohitgr7** [comment]
@anistark when is it?

**Comment by RiteshAgrawal** [comment]
@rohitgr7 It is on July 15 at Cyware Labs, HSR Layout

**Comment by rohitgr7** [comment]
Cool, I can give a talk :)

**Comment by anistark** [comment]
Thanks for confirming @rohitgr7 
Could you please also share your pic to be used in the promotional banner if you're ok with it?

**Comment by rohitgr7** [comment]
> Thanks for confirming @rohitgr7 
> Could you please also share your pic to be used in the promotional banner if you're ok with it?

Sure! Check discord
