### ISSUE TITLE
Time to Ditch requirements.txt and VENV, Start using Poetry now...

### ISSUE THREAD

**Issue by zpratikpathak** [bangpypers/meetup-talks#21]
### Title of the talk

Time to Ditch requirements.txt and VENV, Start using Poetry now...

### Description

Requirements.txt is one of the oldest methods to do package management in Python which leads to many issues, but this is no longer an issue because of new updates of Python. Now you can easily manage your Python project all in one place by using Poetry.
Developers are starting to use Poetry since it's easy to use and easily manageable

### What format do you have in mind for your talk?

Talk

### Table of contents

The talk includes the following points
- What is Package management? Requirements.txt
- Issues with requirements.txt
- How Poetry Solves this Issue
- Installation and uses of Poetry
- Showcase of Important (Poetry Cmds)
- What are .LOCK files? Poetry.Lock
- Separating dev and production packages 
- Creating a Project/Initializing in existing project using poetry
- Managing Virtual Env via Poetry
- Migrating requirements.txt to poetry.lock

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

60

### Prerequisites

Python

### Speaker bio

Pratik Pathak is a highly accomplished technology professional with a passion for sharing his knowledge and expertise with others. As a Microsoft Certified Trainer, Pratik is dedicated to helping individuals and organizations learn how to harness the power of technology to drive business success. With his extensive experience and in-depth understanding of the latest tools and techniques, Pratik is a valuable resource for anyone looking to take their skills to the next level...

In his leisure time, he takes workshops and seminars for students at No Cost. Pratik believes that sharing his expertise and experience is his way of contributing to the world and empowering the next generation of leaders.

LinkedIn - https://www.linkedin.com/in/pathakpratik/
X - https://twitter.com/zpratikpathak

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi @zpratikpathak 

Would you be able to present this talk in Jan 20th meetup?

**Comment by zpratikpathak** [comment]
Count myself in 👍
