### ISSUE TITLE
Create RAG apps for Enterprise Use Cases

### ISSUE THREAD

**Issue by infinite-Joy** [bangpypers/meetup-talks#23]
### Title of the talk

Create RAG apps for Enterprise Use Cases

### Description

Get an understanding of building Retrieval Augmented Generation Apps using GPT powered models. During the talk we will go through the code of a GPT powered HR bot built using llamaindex.

### What format do you have in mind for your talk?

Talk

### Table of contents

- What is RAG: retrieval augmented generation.
- Brief discussion on the different parts of the RAG pipeline.
- Showcase an example chatbot using streamlit, huggingface, llama-index and ollama.

### What domain would you say your talk falls under?

Data Science & Machine Learning

### Duration in minutes (including Q&A)

30

### Prerequisites

python

### Speaker bio

 Senior Machine Learning Staff Engineer at Samsung Semiconductor India R&D with 13 years experience.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi @infinite-Joy 

Are you available on 16th March to present this talk?

**Comment by anistark** [comment]
Hi @infinite-Joy 

Would you be able to present this talk in April meetup?

**Comment by infinite-Joy** [comment]
hi @anistark 
I think you are talking about 20 April right? I will be available.

**Comment by anistark** [comment]
@infinite-Joy We've a slot free this week, 16th March. Would you like to present this month?

**Comment by infinite-Joy** [comment]
yes, 16 March is also fine with me.

**Comment by anistark** [comment]
Thanks. Please find details of the event on [meetup](https://www.meetup.com/bangpypers/events/298623907/).

**Comment by infinite-Joy** [comment]
Hi All.
Thanks for attending the talks. Please find the links below.
PPT: https://github.com/infinite-Joy/webinars/blob/main/creating_gpt_chatbots_for_enterprise_usecases/Create%20RAG%20apps%20for%20Enterprise%20Use%20Cases.pdf
Code: https://github.com/infinite-Joy/webinars/tree/main/creating_gpt_chatbots_for_enterprise_usecases
linkedin: https://www.linkedin.com/in/joydeep-bhattacharjee-934a1157/
twitter: https://twitter.com/alt227Joydeep
