### ISSUE TITLE
From CRUD API to smart apps: Building copilots with Microsoft Semantic Kernel

### ISSUE THREAD

**Issue by rajat-008** [bangpypers/meetup-talks#24]
### Title of the talk

From CRUD API to smart app: Building copilots with Microsoft Semantic Kernel

### Description

The advent of LLMs has opened the floodgates to the development of smart(super smart actually) applications. One such kind of application is co-pilots. 

Remember [this fancy Microsoft demo](https://www.youtube.com/watch?v=fzoZ_f7ji5Q) where you ask for a nice PPT on a certain topic with so and so info, and with just a click you have a sassy PPT ready? Turns out you can build such co-pilots for your own applications.

In this talk, we will walkthrough the process of building a co-pilot around our CRUD API using Microsoft Semantic Kernel.

### What format do you have in mind for your talk?

Talk

### Table of contents

1. LLMs: What are they?
2. Co-pilots? Like those beautiful PowerPoint demos from Microsoft?
3. Co-pilots with LLMs? Enter Microsoft Semantic Kernel
4. Getting our hands dirty: Demo of converting a simple CRUD API into a co-pilot

### What domain would you say your talk falls under?

Data Science & Machine Learning

### Duration in minutes (including Q&A)

30

### Speaker bio

Data Science Engineer at [Thoughtclan Technologies Pvt Ltd](https://www.linkedin.com/company/thoughtclan/). 
Linkedin: https://www.linkedin.com/in/rajat-m-jain/

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi @rajat-008 

Are you available on 16th March to present this talk?

**Comment by rajat-008** [comment]
Yes

**Comment by anistark** [comment]
Please find details of the event on [meetup](https://www.meetup.com/bangpypers/events/298623907/).

**Comment by rajat-008** [comment]
Hey @anistark due to an unforeseen matter needing my attention coming up, I won't be in Bangalore this weekend and hence won't be able to deliver the talk too. Apologies for the inconvenience, I'll make sure I take this talk up the next meetup.

**Comment by anistark** [comment]
Sure. We've April meetup on 27th most probably. Details are yet to finalised. Let me know if you're interested in presenting then.

**Comment by anistark** [comment]
Hey @rajat-008  Do you want to present this in this month meetup on May 18th?

**Comment by nvs-abhilash** [comment]
Hey @rajat-008 are you open to present this talk on 19th October BangPyper's meet-up?

**Comment by anistark** [comment]
No response for a while. Closing for now.
