### ISSUE TITLE
PH7 - An alternative to `Jinja` like templating engines

### ISSUE THREAD

**Issue by angrybayblade** [bangpypers/meetup-talks#25]
### Title of the talk

PH7 - A templating engine that's not annoying to use

### Description

PH7 is an templating engine inspired from JSX and Bable which allows writing HTML using python. It's ridiculously fast to develop templates with and has native CSS and JS support. In this talk I will explain why I developed a new templating engine despite there being several templating engines and how it can help you write more modular, reusable and easy to maintain templates.

Link to PH7's documentation - http://ph7.angrybayblade.me/

### What format do you have in mind for your talk?

Workshop

### Table of contents

* Introduction to PH7
* Why PH7?
* Writing views with PH7
* CSS/JS Support
* Django/Flask integration

### What domain would you say your talk falls under?

Web Dev

### Duration in minutes (including Q&A)

30

### Prerequisites

Web development, Django or Flask

### Speaker bio

Python engineer at [valory-xyz](https://github.com/valory-xyz/), been working on developing multi agent systems for decentralised off-chain compute for past 2 years.

Twitter - https://twitter.com/angrybayblade
LinkedIn - https://www.linkedin.com/in/angrybayblade/

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hey @angrybayblade 

Are you available on 16th March to present this talk?

**Comment by angrybayblade** [comment]
@anistark Yes

**Comment by anistark** [comment]
Please find details of the event on [meetup](https://www.meetup.com/bangpypers/events/298623907/).
