### ISSUE TITLE
Talk - Doing large scale refactors using LibCST

### ISSUE THREAD

**Issue by tusharsadhwani** [bangpypers/meetup-talks#26]
### Title of the talk

Doing large scale refactors using LibCST

### Description

In this talk, we'll learn about how you can write custom code refactorings for Python projects, using LibCST.

LibCST is a concrete syntax tree library for Python, made by Meta. It lets you read and edit Python code in a systematic way.

I'll be demonstrating simple, and a few advanced refactorings that you can do on your codebase with LibCST.

### What format do you have in mind for your talk?

Talk

### Table of contents

- So what is a Concrete Syntax Tree?
- Introduction to CST visitors
- Writing a visitor to upgrade Python syntax
- Doing a large scale refactor using LibCST

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

30

### Prerequisites

None as such. Being able to follow basic Python code, for loops, conditions etc. should be enough.

### Speaker bio

Long term Python developer, author, OSS contributor, and speaker.
Knows a thing or two about Python's internals and language features.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by tusharsadhwani** [comment]
I repurposed this talk as a lightning talk. It's okay to close this if needed.

**Comment by anistark** [comment]
Hey @tusharsadhwani  Do you want to present this in this month meetup on May 18th?

**Comment by tusharsadhwani** [comment]
I'm unavailable this month. Let's do next? (as long as it's after June 12 :D)

**Comment by anistark** [comment]
Can not confirm June at this moment. Will get back.

**Comment by tusharsadhwani** [comment]
Closing this for now, will re-open it if needed.
