### ISSUE TITLE
Talk - Python Interpreter Speed-Ups and Optimization

### ISSUE THREAD

**Issue by pythonhacker** [bangpypers/meetup-talks#27]
### Title of the talk

 Python Interpreter Speed-Ups and Optimization

### Description

Approaches to speeding up Python code inside the interpreter and In this talk we look at examples of this and cover some techniques such as,

1. Quickening with Adaptive Instructions
2. Specialized Instructions
3. Leaner code frames
4. Inlined function calls

These changes are there in the language from Python 3.11 onwards. The talk will cover mostly the changes that were introduced from Python 3.10 -> Python 3.11.

Ref: https://docs.python.org/3.11/whatsnew/3.11.html#faster-cpython

### What format do you have in mind for your talk?

Talk

### Table of contents

1. Quickening with Adaptive Instructions
2. Specialized Instructions
3. Leaner code frames
4. Inlined function calls
5. Code examples

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

45

### Speaker bio

https://twitter.com/skeptichacker
https://fossunited.org/blog/interview/anand-pillai

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Please find details of the event on [meetup](https://www.meetup.com/bangpypers/events/298623907/).

**Comment by pythonhacker** [comment]
This could go upto 45 minutes. I updated the duration @anistark

**Comment by pythonhacker** [comment]
The talk slides and content is available here if anyone is interested - https://github.com/pythonhacker/talks/tree/master/bangpypers/march-2024
