### ISSUE TITLE
[Talk] Creating Secure OTPs: Best Practices

### ISSUE THREAD

**Issue by sayakongit** [bangpypers/meetup-talks#28]
### Title of the talk

Creating Secure OTPs: Best Practices

### Description

I will be presenting on "Creating Secure OTPs: Best Practices." Initially, I'll discuss the importance of OTPs (One-Time Passwords) and highlight different types, such as time-based and HMAC-based OTPs. Additionally, I'll explain why relying solely on random number generators for OTP generation isn't ideal due to potential security threats.

Next, I'll delve into the cryptographic approach used to generate OTPs, emphasizing its role in enhancing security. I'll also introduce the PyOTP Python library, which simplifies the OTP generation process. A live demonstration using PyOTP will illustrate its functionality.

Following the demonstration, I'll open the floor to audience questions, encouraging a deeper understanding of the topic. In conclusion, I'll stress the significance of adhering to secure OTP generation practices to effectively mitigate security risks.

### What format do you have in mind for your talk?

Talk

### Table of contents

- Introduction
- Security Concerns with Random Number Generator OTPs
- Cryptographic Approach to OTP Generation
- Overview of Different OTP Types
- Time-Based OTPs
- HMAC-Based OTPs
- Introduction to PyOTP Python Library
- Features and Functionality of PyOTP
- Live Demo: Generating OTPs with PyOTP
- Audience QnA

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

20

### Prerequisites

Basic knowledge of Python.

### Speaker bio

I am a Systems Engineer at TCS with a passion for community engagement and open source contributions. I have worked as a full stack developer with Python based frameworks such as Django, Flask etc. and all major JavaScript frameworks. Throughout my career, I've attended, organized, and spoken at numerous community events, sharing insights and experiences with fellow enthusiasts. As an active open source contributor and maintainer, I strive to foster collaboration and innovation within the developer community.

LinkedIn: https://www.linkedin.com/in/sayaksaha10/
Twitter: https://twitter.com/10_sayak

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hey @sayakongit Do you want to present this in this month meetup on May 18th?

**Comment by sayakongit** [comment]
> Hey @sayakongit Do you want to present this in this month meetup on May 18th?

Hey @anistark, yes sure.

**Comment by sayakongit** [comment]
Hi @anistark, the meet-up is happening on 18th?

**Comment by anistark** [comment]
@sayakongit Yes

**Comment by anistark** [comment]
@sayakongit We had to cancel May meetup but will you be able to present in June meetup?

**Comment by sayakongit** [comment]
Hi @anistark, yes I will be available on 22nd of June.

**Comment by anistark** [comment]
@sayakongit There's a slight scheduling conflict.
Are you available on 15th?

**Comment by sayakongit** [comment]
@anistark It would be difficult to manage on 15th. If possible, I can join the following month.

**Comment by anistark** [comment]
@sayakongit July meetup is on 13th. Will that work for you?

**Comment by sayakongit** [comment]
> @sayakongit July meetup is on 13th. Will that work for you? 

Yes, I'll be available on 13th.

**Comment by RiteshAgrawal** [comment]
@sayakongit Can you please share your headshot here. It is required for the meetup poster.

**Comment by anistark** [comment]
> @sayakongit Can you please share your headshot here. It is required for the meetup poster.

@sayakongit gentle reminder on this.

**Comment by anistark** [comment]
@sayakongit is it ok to use your linkedin pic?

**Comment by sayakongit** [comment]
Hi @anistark, yes please! You can go ahead with the LinkedIn picture.
