### ISSUE TITLE
The Python type system 

### ISSUE THREAD

**Issue by nikochiko** [bangpypers/meetup-talks#3]
### Title of the talk

The Python Type System

### Description

Python's type system is as absurd as it is fascinating. "Everything is an object" is an understatement. In this talk, 
In this talk, we will take a look at how Python's type system is implemented -- specifically its objects and classes. We'll take a look at how classes are also objects, the consequences of that,  and how it is implemented in the interpreter.
Next, we'll try to figure out where the `self` in method comes from.
We'll top it off with how we can create a function decorator that will take away the need for a class keyword.

**Outcomes:**
- Familiarity with classes as objects
- Getting known to confusing behaviour
- Exploring `PyObject` from the CPython interpretr

### What format do you have in mind for your talk?

Talk

### Table of contents

**Outline:**
- `object` and `type`
- `PyObject`, `PyTypeObject`, and `*PyObject`
- Where does `self` come from in methods?
- Descriptors
- The function decorator that makes `class` keyword redundant
- Why it's not exactly the same as the `class` keyword

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

25

### Speaker bio

Software Developer at Pipal Academy

- Python, Haskell, OCaml, ...
- Interested in programming languages
- Recently started contributing to the OCaml Multicore project
- Self-Hosting hobbyist
- Projects: [autosaved](https://github.com/nikochiko/autosaved), [kutty](https://github.com/pipalacademy/kutty), [capstone](https://github.com/pipalacademy/capstone), [metapy](https://github.com/nikochiko/metapy), [...](https://github.com/nikochiko)

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi 👋🏼 

Please confirm if you want to present this talk at [this month's meetup](https://www.meetup.com/bangpypers/events/whqxvsyfcfbxb/)?

**Comment by nikochiko** [comment]
Hi yes. I'd like to present it this month
