### ISSUE TITLE
Creating streamlit apps using NCBI Apis and Google gemini.

### ISSUE THREAD

**Issue by BioinfoGuy10** [bangpypers/meetup-talks#30]
### Title of the talk

Data curation copilots using streamlit

### Description

The talk will focus on these aspects:
1) The need for data curation in the lifescience/healthcare field.
2) How does an data curation MVP created using streamlit address this gap.
3) What are the different NCBI(National Center for Biotechnology Information) Apis  available.
4) How does Gemini fit into all this?

### What format do you have in mind for your talk?

Talk

### Table of contents

The talk will focus on these aspects:
1) The need for data curation in the lifescience/healthcare field.
2) How does an data curation MVP created using streamlit address this gap.
3) What are the different NCBI(National Center for Biotechnology Information) Apis  available.
4) How does Gemini fit into all this?

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

25-30 mins.

### Speaker bio

I am a bioinformatician by profession. I have been programming in python for a couple of years now. Constantly thinking about how to use LLMs to automate stuff.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hey @BioinfoGuy10  Do you want to present this in this month meetup on May 18th?

**Comment by BioinfoGuy10** [comment]
Hey, I'm out of station next week. Could i do this on June meeting, the
15th?

**Comment by anistark** [comment]
Can not confirm June at this moment. Will get back.

**Comment by anistark** [comment]
@BioinfoGuy10 June 15th meetup do you want to confirm?

**Comment by anistark** [comment]
We had slight scheduling update. @BioinfoGuy10 can you confirm if you're available on 15th ?

**Comment by BioinfoGuy10** [comment]
Yes. I am available
