### ISSUE TITLE
Talk: Replacing pyinstaller with 100 lines of code

### ISSUE THREAD

**Issue by tusharsadhwani** [bangpypers/meetup-talks#31]
### Title of the talk

Replacing pyinstaller with 100 lines of code

### Description

If you have ever struggled with figuring out how to ship a Python application to a friend, customer or anyone, that is about to change.

While tools like `pyinstaller` have existed for a long time, they are not very straightforward to use, and are complex tools with their sets of bugs, limitations and so on.

A few things around Python have changed, such that it's much easier today to package and ship a Python application now. And to make it even more simple, I created a tool called `packaged`.

Let's figure out how it works, and how you can use it to ship Python applications with ease.

### What format do you have in mind for your talk?

Talk

### Table of contents

- Why are Python apps hard to ship?
- The first puzzle piece: Building `yen`
- The second puzzle piece: `makeself`
- Putting them together: how `packaged` works
- Demo: Using `packaged` to create portable Python applications

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

30

### Prerequisites

Understanding basic Python concepts, pip, etc. is all that's needed.

### Speaker bio

Long-term Python developer, author, OSS contributor and speaker, Tushar currently works as a Software Engineer building language tools at DeepSource.

When not working, he tries to contribute to the Python developer tools ecosystem, like black, ruff, flake8 and mypy.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@tusharsadhwani are you available on 15th ?

**Comment by tusharsadhwani** [comment]
Yes, I'm available
