### ISSUE TITLE
Zango - New Python Web framework for building enterprise-ready custom business applications

### ISSUE THREAD

**Issue by shahharsh176** [bangpypers/meetup-talks#32]
### Title of the talk

Zango - New Python Web framework for building enterprise-ready custom business applications

### Description

[Zango](https://github.com/Healthlane-Technologies/Zango), built on top of Django, is further opinionated towards building enterprise-ready custom business apps. Includes additional batteries for out-of-the-box enterprise readiness and rapid app development. Growing ecosystem of packages that serve as building blocks of apps.

Zango also enables multi-tenancy where each tenant, representing an app, can be deployed independently on the same underlying monolith. Tenants have logically seperated db, codebase as well as deployment. This significantly cuts down per app hosting cost.

Github repo:  https://github.com/Healthlane-Technologies/Zango
Docs: https://www.zango.dev/docs

I am one of the maintainers of Zango and would like to present the strengths and get the community's feedback on the Zango framework to the community.

### What format do you have in mind for your talk?

Talk

### Table of contents

- What are Custom Business Applications?
- Introduction to the Zango Framework
- Deep Dive into Zango Architecture
- Demo of App Development

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

30

### Prerequisites

Basic Knowledge of Django and the overall idea of application development 

### Speaker bio

I am a Software Engineer at Zelthy with a background in backend development and a passion for problem-solving. As one of the maintainers of the Zango framework, I am eager to showcase its strengths to the community.

LinkedIn: https://www.linkedin.com/in/shahharsh176/

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@shahharsh176 It's kinda short notice but we've 1 slot in June meetup. You want to present this Saturday?

**Comment by shahharsh176** [comment]
@anistark Yes, I am available on this Saturday.

**Comment by anistark** [comment]
Great. Confirming your talk then. See you tomorrow.
