### ISSUE TITLE
Talk - "pip install new syntax"

### ISSUE THREAD

**Issue by tusharsadhwani** [bangpypers/meetup-talks#35]
### Title of the talk

pip install new syntax

### Description

In the past few projects of mine, I've tinkered with adding new syntax to Python. There's many different approaches for doing it, but they're all really cumbersome and hard to maintain and use together.

So I decided it is time to create a framework that lets you do that.

Do you want to use something like JSX in your Python code? Do you like the `|>` operator from Elixir, or the `?.` operator from JavaScript?

All of that, and more, is now possible with a new framework called `new_syntax`.

### What format do you have in mind for your talk?

Talk

### Table of contents

- Why add new syntax to Python
- How does this even work
- Composition, and the possibilities that open up with `new_syntax`.

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

30

### Prerequisites

No pre requisites, other being able to understand simple Python code.

### Speaker bio

Python + OSS code monkey, writer and speaker, keeps inventing packages that no-one uses, usually. Sometimes they get really popular and maintaining them becomes an unexpected burden, but enjoys it nonetheless.

Blog: https://tushar.lol
Twitter: https://twitter.com/tusharisanerd
GitHub: https://github.com/tusharsadhwani

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by nvs-abhilash** [comment]
@tusharsadhwani are you open to presenting this talk on 19th October BangPyper's meet-up?

**Comment by tusharsadhwani** [comment]
I have other commitments that weekend. Can we do next month?

**Comment by tusharsadhwani** [comment]
Actually nevermind, I'll present on 19th, it's in the afternoon right.

**Comment by nvs-abhilash** [comment]
First half from 10:30.

**Comment by tusharsadhwani** [comment]
works for me.
