### ISSUE TITLE
Finance for software professional

### ISSUE THREAD

**Issue by manishjhanwar** [bangpypers/meetup-talks#38]
### Title of the talk

Finance for software professional

### Description

Understanding the perspective of money for software professional
Also sharing the corporate learning

### What format do you have in mind for your talk?

Talk

### Table of contents

Understanding the perspective of money for software professional
Also sharing the corporate learning

### What domain would you say your talk falls under?

Research

### Duration in minutes (including Q&A)

30

### Speaker bio

14 years experience in IT

Linkedin
https://www.linkedin.com/in/manish-jhanwar-b8647945

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@manishjhanwar Can you please share more details about what your talk is supposed to cover?

**Comment by manishjhanwar** [comment]
Hi,

This is more about in general talk where we educate young people of how to
manage finance and sharing our learning from corporate world while keeping
the base as software engineering.

Regards
Manish

**Comment by anistark** [comment]
Thanks @manishjhanwar 

But, do you've an overview plan on what all would be covered? Highlight any particular example that you'd want to cover as well.
Would help us in alligning with if it fits this audience.

Also, if it's more inspirational, personal life story drawn, aspirational, debate, or other formats... and so on.

**Comment by manishjhanwar** [comment]
Hi

It will definitely fit the audience.
I have done more than 200 times.
Have started this series after realizing that software people are generally
good in development but very bad in managing money and generally in debt.
So this kind of talk help them in giving open perspective and force
audience to think about there finance explicitly.

Anyway I understand that given that we are python community so we expect
people to talk more about python. But believe, since we are community, we
should also help our people in these core area of finance before it gets
late.

Last thing from my side , if you wish, You can exclude this from agenda for
now and based on time we can decide that day.   That is also fine.


Regards,
Manish

**Comment by anistark** [comment]
Sorry, but unless I see a detailed plan on what all will be covered in the talk, I'm not finding enough confidence to clear it for a full talk. If you've presented it earlier, I'm sure there'll be recordings, slides or other doc showcasing what's on agenda.

**Comment by manishjhanwar** [comment]
Sure. No worries.

Thank you.

**Comment by anistark** [comment]
Still don't see any detailed description. Closing it for now.
