### ISSUE TITLE
Fictional Commentator using Streamlit + Google's Vertex AI

### ISSUE THREAD

**Issue by indiVar0508** [bangpypers/meetup-talks#39]
### Title of the talk

Fictional Commentator using Streamlit + Google's Vertex AI

### Description

Fictional commentator is a personal pet project that uses streamlit and any LLM model (currently google's gemini via VertexAI) to commentate on a live international cricket match.
There few characters from some popular sitcom's of which the LLM takes persona of and tries to summarize match state at that point in time.
This project also has a X bot that uses same LLM model to post tweet of a live match on Sunday scheduled using github actions in one the sitcom character 
 persona's

Demo : https://fictionalcommentator.streamlit.app/
Twitter/X handle of bot : https://x.com/fictnlcmttr

### What format do you have in mind for your talk?

Talk

### Table of contents

- Intro
- What is Fictional Commentator
- Streamlit component walkthrough
- Vertex AI setup walkthrough
- X bot setup walkthrough using github actions

### What domain would you say your talk falls under?

AI

### Duration in minutes (including Q&A)

30

### Prerequisites

NA

### Speaker bio

Hi I am Indivar, I am passionate about RL and making small 2d games, I do some opensource and learn new things.
I currently work as a Software Engineer 2

Linkdin: https://www.linkedin.com/in/indivar-mishra/
github: https://github.com/indiVar0508
twitter: https://x.com/indimishra08

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by nvs-abhilash** [comment]
@indiVar0508 , are you available to present it on the 19th October meet-up?

**Comment by indiVar0508** [comment]
Yes I am available

**Comment by nvs-abhilash** [comment]
@indiVar0508 , can you please fill this Google form so that the organizers can contact you: https://forms.gle/cRx2RPnPbXKkmP2f9

**Comment by indiVar0508** [comment]
Hi abhilash, I have submitted the form
