### ISSUE TITLE
Introduction to Q Learning with gymnasium

### ISSUE THREAD

**Issue by indiVar0508** [bangpypers/meetup-talks#42]
### Title of the talk

Introduction to Q Learning with gymnasium

### Description

Q learning is a reinforcement learning algorithm used to build simple agents to learn and evolve in environment (be it game or some business specific environment) the talk intends to give a brief overview of working of algorithm, high level overview of deep Q networks and a small demo on how one can play around with it with [gymnasium](https://github.com/Farama-Foundation/Gymnasium).

### What format do you have in mind for your talk?

Talk

### Table of contents

- Introduction to Reinforcement Learning
- Common terminologies / Lingo
- What is Q learning?
- What is DQN and when is it needed?
- Demo with gymnasium [5-8 mins]

### What domain would you say your talk falls under?

AI

### Duration in minutes (including Q&A)

30

### Speaker bio

Hi I am Indivar, I am passionate about RL and making small 2d games, I do some opensource and learn new things.
I currently work as a Software Engineer 2

Linkdin: https://www.linkedin.com/in/indivar-mishra/
github: https://github.com/indiVar0508
twitter: https://x.com/indimishra08

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by nvs-abhilash** [comment]
@indiVar0508 are you available to present it on 23rd Nov 2024?

**Comment by indiVar0508** [comment]
I can present
