### ISSUE TITLE
Rolling with Python: A Deep Dive into Wheels

### ISSUE THREAD

**Issue by abhiksark** [bangpypers/meetup-talks#44]
### Title of the talk

Rolling with Python: A Deep Dive into Wheels

### Description

in this talk will go deep-dive into wheels: 
- What they are ? 
- Why it is needed
- Why each platform (mac, linux) has it's own wheels.
- What are best practices for wheels creation. 

### What format do you have in mind for your talk?

Talk

### Table of contents

- Intro to wheels: How did we transition from eggs to wheels? 
- Understanding Wheels structure. 
- Deep dive into numpy/torch wheels and understand why they are big. 
- Standard Conventions around Wheels. (esp around naming wheels)

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

30 mins 

### Prerequisites

installation of any package manager. 

### Speaker X(Twitter): Account link (Optional)

x.com/abhiksark 

### Speaker bio

Abhik Sarkar is the Head of Machine Learning at Cloudastructure, Inc., where he creates computer vision solutions for security. Abhik is passionate about diving into the core of Python, exploring its nuances, and continually expanding his expertise.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by nvs-abhilash** [comment]
@abhiksark are you available to present the talk on 23rd Nov 2024?

**Comment by abhiksark** [comment]
@nvs-abhilash any tentative time?

**Comment by nvs-abhilash** [comment]
Morning 10:30 AM to 1PM

**Comment by abhiksark** [comment]
@nvs-abhilash i can present!
