### ISSUE TITLE
AI Wrapped 2024

### ISSUE THREAD

**Issue by amrrs** [bangpypers/meetup-talks#45]
### Title of the talk

AI Wrapped 2024

### Description

This talk would provide the summary of the state of AI in 2024 - with the most recent information about LLMs and models of other modalities. 

Note: This is not a Pure Python talk, It's more around year-end update. I proposed this topic given this is the last event of the year. Happy to change it to something else if the organizing team feels something else is better

### What format do you have in mind for your talk?

Talk

### Table of contents

AI Wrapped 2024
* Where did we end 2023 
* Top LLMs of 2024 & Demos if applicable
* Top Image generation models & Demos if applicable
* Top Video generation models & Demos if applicable
* Agentic Tools & Demos if applicable
* Looking forward in 2024

### What domain would you say your talk falls under?

AI

### Duration in minutes (including Q&A)

30-50 mins (this can be covered for an hour as well) 

### Prerequisites

Nothing! 

### Speaker X(Twitter) Account link (Optional)

https://twitter.com/1littlecoder

### Speaker bio

An Educator teaching AI to Humans - https://youtube.com/c/1littlecoder

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@amrrs Are you available to present this talk on 21st December ?

**Comment by amrrs** [comment]
Yes @anistark

**Comment by amrrs** [comment]
Just please let me know how long the talk should be, I'll prep accordingly, Thanks @anistark

**Comment by anistark** [comment]
Better if around 30 mins. If you need longer, you can let me know, we can adjust agenda accordingly.

**Comment by amrrs** [comment]
I'll try to keep it to 30 then

**Comment by amrrs** [comment]
@anistark - just saw the schedule, it's okay to mention my name as "Abdul Majed" in case if that'll help. 
sorry i thought I'd mentioned before. 

Also if the 12-12:30 slot is not filled, I'd glad if I can get 15 mins from it!

**Comment by amrrs** [comment]
Thank you for the opportunity - here's the slidepack presented during the meetup - https://docs.google.com/presentation/d/1OzOEm2uYDHBOJT07oYqKLzNt5a7NLCW5Wma2Q1GubkA/edit?usp=sharing
