### ISSUE TITLE
Python and Numbers: Digits, Datatypes, and Performance

### ISSUE THREAD

**Issue by abhiksark** [bangpypers/meetup-talks#46]
### Title of the talk

Python and Numbers: Digits, Datatypes, and Performance

### Description

Numbers are the backbone of programming, and in Python, they come in many forms: integers, floats, decimals
How do These different representations affect performance and precision, especially with the advent of Quantized Models, they have evolved. 

### What format do you have in mind for your talk?

Talk

### Table of contents

Table of Contents

    Introduction to Numbers in Python:
        A historical perspective: Python’s numerical landscape from int and float to Decimal and beyond.

    Representation and Trade-offs:
        Precision vs. Performance: Why every bit counts.
        Understanding how Python handles numbers under the hood.

    Emerging Datatypes:
        A closer look at bfloat16, float8, and float4.
        Real-world use cases in Machine Learning, Deep Learning, and beyond.

    Performance Benchmarks:
        How numerical choices affect performance in Python.
        Benchmarks and practical tips for optimizing performance.

### What domain would you say your talk falls under?

Data Science & Machine Learning

### Duration in minutes (including Q&A)

25

### Speaker X(Twitter) Account link (Optional)

x.com/abhiksark

### Speaker bio

Abhik Sarkar is the Head of Machine Learning at Cloudastructure, Inc., where he creates cutting-edge computer vision solutions for security. With over 8 years of Python experience, Abhik is deeply passionate about diving into Python’s core features, exploring numerical computation, and understanding the interplay of performance and precision in real-world applications.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@abhiksark are you available to present this talk at December 21st meetup?

**Comment by abhiksark** [comment]
@anistark yes I am.

**Comment by abhiksark** [comment]
@anistark I'm cold and bad sore throat.
Don't think that I'll be able to make it today.

**Comment by anistark** [comment]
That's too bad. Get well soon.

I guess we'll have the first talk cancelled then.
