### ISSUE TITLE
Talk On Introduction to RobotFramework [CFP]

### ISSUE THREAD

**Issue by dhilipsiva** [bangpypers/meetup-talks#5]
### Title of the talk

Introduction to RobotFramework

### Description

I would like to introduce RobotFramework and how it can be used for Acceptance Test Driven Development (ATDD)

### What format do you have in mind for your talk?

Talk

### Table of contents

* Introduction To RobotFramework
    * BuiltIns
    * OperatingSystem
    * Collections
* Writing Custom keywords
* Intro to RF-SeleniumLibrary
* A simple user story and acceptance test

### What domain would you say your talk falls under?

Testing

### Duration in minutes (including Q&A)

45

### Prerequisites

* Install RobotFramework and SeleniumLibrary `pip install robotframework-seleniumlibrary`
* A web driver for your browser: https://github.com/SergeyPirogov/webdriver_manager#use-with-chrome

### Speaker bio

I am a passionate and experienced Software Architect/Engineer with a diverse skill set and a wealth of experience in various programming languages and technologies. Currently, I work as a Software Architect at Appknox. I actively contribute to numerous repositories on GitHub. You can contact me through my email dhilipsiva@pm.me. You can find my past experiences on LinkedIn and search for me on Google. I am passionate about Python, Rust & WebAssembly.

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi @dhilipsiva 

Would you be able to present this month? 20th May morning.
We're also designing a poster this time as an experiment. Would you be open to sharing your pic to be put up on the poster?

**Comment by dhilipsiva** [comment]
Hi @anistark , sure 20th may works. How do I send you my picture?

**Comment by RiteshAgrawal** [comment]
@dhilipsiva You can add here as a comment

**Comment by dhilipsiva** [comment]
@RiteshAgrawal @anistark Here is my picture
![PXL_20230413_082204825 PORTRAIT](https://user-images.githubusercontent.com/502170/237055485-c2cd80c7-3b0e-4ad1-b267-25320a829c23.jpg)

**Comment by dhilipsiva** [comment]
@RiteshAgrawal @anistark I think there was a small mistake in the poster: https://www.meetup.com/bangpypers/events/whqxvsyfchbbc/

Arjoon is not from Appknox. :stuck_out_tongue:

**Comment by anistark** [comment]
> @RiteshAgrawal @anistark I think there was a small mistake in the poster: https://www.meetup.com/bangpypers/events/whqxvsyfchbbc/
> 
> Arjoon is not from Appknox. 😛

My bad. Will fix it.

**Comment by RiteshAgrawal** [comment]
Hi @dhilipsiva 
Can you please share your official mail id to me on discord. My handle is `k3ypnchr#5133`. This is required for internet access at venue.

**Comment by dhilipsiva** [comment]
@RiteshAgrawal Apologies, I could not find you by your tag on Discord. Was only able to send a friend request. Please accept so I can DM you. Or you can find me by my tag: `dhilipsiva#9674`
