### ISSUE TITLE
Jayporeci.in | A zero setup CI system

### ISSUE THREAD

**Issue by theSage21** [bangpypers/meetup-talks#6]
### Title of the talk

Jayporeci.in | A zero setup CI system

## Goals for the talk

- I've built and have been using https://jayporeci.in for my projects for a while now
- I want to promote the project and get feedback about it.

## About the project

- Offline and local first
- We can configure pipelines in Python
- Jobs are run using [Docker](https://www.docker.com/); on your laptop and on cloud IF needed.
- Send status reports anywhere, or nowhere at all.
    - Email, commit to git, Gitea PR, Github PR, or write your own class and send it to slack / telegram etc.

### What format do you have in mind for your talk?

Talk

### Table of contents

- When would you want to use such a system, when to avoid it.
- Things it can do that you cannot do with other systems.
- A few features that are hard to do in other systems.
- I'll walk through an old project and show how to install it on that project, as well as start using it instantly.

### What domain would you say your talk falls under?

CLI & Tooling

### Duration in minutes (including Q&A)

30 minutes

### Prerequisites

If you want to follow along, please bring a machine that has docker and git installed on it. It should have access to the internet for the demo to work.

### Speaker bio

- https://twitter.com/arjoonn1
- @arjoonn on telegram is more reachable

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by theSage21** [comment]
Hi, Is there any way to know early on if this talk is confirmed? I'll need to book tickets to come to Blr :sweat_smile:

**Comment by theSage21** [comment]
> 

Well, 2-1 weeks in advance would be good. Otherwise prices are almost 3x it seems.

**Comment by anistark** [comment]
I understand. If you want to come in for this month, feel free to plan for next month perhaps?

**Comment by theSage21** [comment]
I think if this gets confirmed I'll try and make it, otherwise next month :D

**Comment by anistark** [comment]
Please share a pic of yours if you're ok with it.

**Comment by theSage21** [comment]
Ah sure sure ! Would this work?

![image](https://github.com/bangpypers/meetup-talks/assets/7693265/7b0b26ef-f1e8-487b-9afa-f8ce3648e4af)

**Comment by RiteshAgrawal** [comment]
Hi @theSage21 
Can you please DM your official mail id to me on discord. My handle is `k3ypnchr#5133`. 
This is required for internet access at venue.

**Comment by theSage21** [comment]
I've sent you a request. I'm new to discord so bear with me :D
