### ISSUE TITLE
Cobrapy-Metabolic Flux Balance Analysis

### ISSUE THREAD

**Issue by BioinfoGuy10** [bangpypers/meetup-talks#7]
### Title of the talk

Cobrapy-Metabolic Flux Balance Analysis

### Description

I will talk about Flux balance analysis.
How A culture medium in a laboratory is done.
How a python package, cobrapy can be used to predict the amount of amino acids to be used to make a culture medium.

### What format do you have in mind for your talk?

Talk

### Table of contents

I will talk about Flux balance analysis.
How A culture medium in a laboratory is done.
How a python package, cobrapy can be used to predict the amount of amino acids to be used to make a culture medium.

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

20

### Prerequisites

A projector to show ppt

### Speaker bio

https://www.linkedin.com/in/keith-saldanha-3bb590aa/

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
@BioinfoGuy10 Do you want to present in this month's meetup or next month?

**Comment by BioinfoGuy10** [comment]
Can I do July, please?

**Comment by anistark** [comment]
Hi @BioinfoGuy10 

For sure. Will keep it up for July and get back to you with more details.

**Comment by BioinfoGuy10** [comment]
Thanks a lot.

**Comment by BioinfoGuy10** [comment]
Sure. Happy to.

**Comment by anistark** [comment]
Could you please also share your pic to be used in the promotional banner if you're ok with it?
And your twitter if you're active on twitter.

**Comment by BioinfoGuy10** [comment]
I am not on Twitter but here's my LinkedIn profile if that helps.
https://www.linkedin.com/in/keith-saldanha-3bb590aa
