### ISSUE TITLE
Talk proposal: Writing a Python interpreter from scratch, in half an hour.

### ISSUE THREAD

**Issue by tushar-deepsource** [bangpypers/meetup-talks#9]
### Title of the talk

Writing a Python interpreter from scratch, in half an hour.

### Description

You use the Python interpreter every single day. It does a lot of things for you: checks that your code has valid syntax and is properly indented, imports modules from various locations, and runs your code instruction-by-instruction.

But if you've ever wondered how exactly it happens, this talk will teach you the entire process, by building a working python interpreter from scratch.

### What format do you have in mind for your talk?

Talk

### Table of contents

The plan is to write a really simple, but working Python interpreter that can run Python code, from scratch.

The concepts we'll be going through to build this interpreter:

- Parsing an indentation based language
- Why `Indent` and `Dedent` need to be tokens
- Writing a Recursive Descent parser
- Parsing literals: `int`s, strings, lists, dictionaries
- Parsing expressions
- Parsing function calls - `print("Hello world!")`
- Semantic analysis: removing invalid code
- A tree-walk interpreter
- Interpreting `print()` statements
- Running `import` statements
- File I/O: implementing `open()` calls
- Running `json.loads()` and `json.dumps()` on our hand-written interpreter

### What domain would you say your talk falls under?

Core Python

### Duration in minutes (including Q&A)

40

### Prerequisites

A working knowledge of basic Python concepts would be good, since the talk will feature a lot of live coding.

Knowledge of any Python library is not needed.

### Speaker bio

Tushar is a Python developer, author, technical reviewer and speaker.

Currently working at DeepSource, his main topics of interest are metaprogramming, static analysis, and type checking.

Twitter: https://twitter.com/sadhlife

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release
the video on [BangPyper's YouTube
channel](https://www.youtube.com/channel/UCIYL-l3N9VLFbqMum40D-1w)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://bangalore.pythonindia.org/coc/)

**Comment by anistark** [comment]
Hi @tushar-deepsource  
Are you willing to present this in July meetup?

**Comment by tusharsadhwani** [comment]
Sure, but I'm out of the country between 17 and 25. If the dates allow for it, I'd love to.

**Comment by anistark** [comment]
Oh. In that case, let me get back to you with date confirmations. Most likely it's on 22nd. But will confirm.

**Comment by anistark** [comment]
@tushar-deepsource It's on 15th July. Works for you?

**Comment by anistark** [comment]
Could you please also share your pic to be used in the promotional banner if you're ok with it?

**Comment by tusharsadhwani** [comment]
Works for me.

**Comment by tushar-deepsource** [comment]
I also have an uncropped version of this image somewhere. If you need that, I can get it.

**Comment by tusharsadhwani** [comment]
@anistark what's the venue?

**Comment by anistark** [comment]
@tushar-deepsource Image is fine. Thanks.
Location is in Cyware, HSR. (most probably)
